// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZQaTPRE0kN69jeQGrRGhSnaAgeTWXA5w',
    appId: '1:384213422885:android:fbb046d67d515dfbd900cc',
    messagingSenderId: '384213422885',
    projectId: 'notes-flutter-240e6',
    storageBucket: 'notes-flutter-240e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWOWyCcjXnqjsFaYUi-uE3tFT8LJlS6eU',
    appId: '1:384213422885:ios:44fa34c278650434d900cc',
    messagingSenderId: '384213422885',
    projectId: 'notes-flutter-240e6',
    storageBucket: 'notes-flutter-240e6.appspot.com',
    iosClientId: '384213422885-09sqns3cnrlft5cq8aehm4lg5kc7cbjj.apps.googleusercontent.com',
    iosBundleId: 'com.fullscale.notes',
  );
}
